cc = {"AFGHANISTAN":"AF","LAND ISLANDS":"AX","ALBANIA":"AL","ALGERIA":"DZ","AMERICAN SAMOA":"AS","ANDORRA":"AD","ANGOLA":"AO","ANGUILLA":"AI","ANTARCTICA":"AQ","ANTIGUA AND BARBUDA":"AG","ARGENTINA":"AR","ARMENIA":"AM","ARUBA":"AW","AUSTRALIA":"AU","AUSTRIA":"AT","AZERBAIJAN":"AZ","BAHAMAS":"BS","BAHRAIN":"BH","BANGLADESH":"BD","BARBADOS":"BB","BELARUS":"BY","BELGIUM":"BE","BELIZE":"BZ","BENIN":"BJ","BERMUDA":"BM","BHUTAN":"BT","BOLIVIA, PLURINATIONAL STATE OF":"BO","BOLIVIA":"BO","BONAIRE, SINT EUSTATIUS AND SABA":"BQ","BOSNIA AND HERZEGOVINA":"BA","BOTSWANA":"BW","BOUVET ISLAND":"BV","BRAZIL":"BR","BRITISH INDIAN OCEAN TERRITORY":"IO","BRUNEI DARUSSALAM":"BN","BULGARIA":"BG","BURKINA FASO":"BF","BURUNDI":"BI","CAMBODIA":"KH","CAMEROON":"CM","CAMEROUN":"CM","CANADA":"CA","CAPE VERDE":"CV","CAYMAN ISLANDS":"KY","CENTRAL AFRICAN REPUBLIC":"CF","CHAD":"TD","CHILE":"CL","CHINA":"CN","CHRISTMAS ISLAND":"CX","COCOS (KEELING) ISLANDS":"CC","COLOMBIA":"CO","COMOROS":"KM","CONGO":"CG","DEMOCRATIC REPUBLIC OF THE CONGO":"CD","COOK ISLANDS":"CK","COSTA RICA":"CR","COTE D'IVOIRE":"CI","IVORY COAST":"CI","CROATIA":"HR","CUBA":"CU","CURACAO":"CW","CYPRUS":"CY","CZECH REPUBLIC":"CZ","DENMARK":"DK","DJIBOUTI":"DJ","DOMINICA":"DM","DOMINICAN REPUBLIC":"DO","ECUADOR":"EC","EGYPT":"EG","EL SALVADOR":"SV","EQUATORIAL GUINEA":"GQ","ERITREA":"ER","ESTONIA":"EE","ETHIOPIA":"ET","FALKLAND ISLANDS (MALVINAS)":"FK","FALKLAND ISLANDS":"FK","FAROE ISLANDS":"FO","FIJI":"FJ","FINLAND":"FI","FRANCE":"FR","FRENCH GUIANA":"GF","FRENCH POLYNESIA":"PF","FRENCH SOUTHERN TERRITORIES":"TF","GABON":"GA","GAMBIA":"GM","GEORGIA":"GE","GERMANY":"DE","GHANA":"GH","GIBRALTAR":"GI","GREECE":"GR","GREENLAND":"GL","GRENADA":"GD","GUADELOUPE":"GP","GUAM":"GU","GUATEMALA":"GT","GUERNSEY":"GG","GUINEA":"GN","GUINEA BISSAU":"GW","GUYANA":"GY","HAITI":"HT","HEARD ISLAND AND MCDONALD ISLANDS":"HM","HOLY SEE (VATICAN CITY STATE)":"VA","HONDURAS":"HN","HONG KONG":"HK","HUNGARY":"HU","ICELAND":"IS","INDIA":"IN","INDONESIA":"ID","IRAN, ISLAMIC REPUBLIC OF":"IR","IRAN":"IR","IRAQ":"IQ","IRELAND":"IE","ISLE OF MAN":"IM","ISRAEL":"IL","ITALY":"IT","JAMAICA":"JM","JAPAN":"JP","JERSEY":"JE","JORDAN":"JO","KAZAKHSTAN":"KZ","KENYA":"KE","KIRIBATI":"KI","KOREA, NORTH (DPRK)":"KP","KOREA, SOUTH (ROK)":"KR","NORTH KOREA":"KP","SOUTH KOREA":"KR","KUWAIT":"KW","KYRGYZSTAN":"KG","LAO PEOPLE'S DEMOCRATIC REPUBLIC":"LA","LAOS":"LA","LATVIA":"LV","LEBANON":"LB","LESOTHO":"LS","LIBERIA":"LR","LIBYA":"LY","LIECHTENSTEIN":"LI","LITHUANIA":"LT","LUXEMBOURG":"LU","MACAO":"MO","MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF":"MK","MADAGASCAR":"MG","MALAWI":"MW","MALAYSIA":"MY","MALDIVES":"MV","MALI":"ML","MALTA":"MT","MARSHALL ISLANDS":"MH","MARTINIQUE":"MQ","MAURITANIA":"MR","MAURITIUS":"MU","MAYOTTE":"YT","MEXICO":"MX","MICRONESIA, FEDERATED STATES OF":"FM","MICRONESIA (FEDERATED STATES OF)":"FM","MOLDOVA, REPUBLIC OF":"MD","MONACO":"MC","MONGOLIA":"MN","MONTENEGRO":"ME","MONTSERRAT":"MS","MOROCCO":"MA","MOZAMBIQUE":"MZ","MYANMAR":"MM","BURMA":"MM","NAMIBIA":"NA","NAURU":"NR","NEPAL":"NP","NETHERLANDS":"NL","NEW CALEDONIA":"NC","NEW ZEALAND":"NZ","NICARAGUA":"NI","NIGER":"NE","NIGERIA":"NG","NIUE":"NU","NORFOLK ISLAND":"NF","NORTHERN MARIANA ISLANDS":"MP","NORWAY":"NO","OMAN":"OM","PAKISTAN":"PK","PALAU":"PW","PALESTINIAN TERRITORY, OCCUPIED":"PS","PANAMA":"PA","PAPUA NEW GUINEA":"PG","PARAGUAY":"PY","PERU":"PE","PHILIPPINES":"PH","PITCAIRN":"PN","POLAND":"PL","PORTUGAL":"PT","PUERTO RICO":"PR","QATAR":"QA","REUNION":"RE","ROMANIA":"RO","RUSSIA":"RU","RUSSIAN FEDERATION":"RU","RWANDA":"RW","SAINT BARTHELEMY":"BL","SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA":"SH","ST. HELENA":"SH","SAINT KITTS AND NEVIS":"KN","ST. KITTS-NEVIS":"KN","SAINT LUCIA":"LC","ST. LUCIA":"LC","SAINT MARTIN (FRENCH PART)":"MF","SAINT PIERRE AND MIQUELON":"PM","ST. PIERRE AND MIQUELON":"PM","SAINT VINCENT AND THE GRENADINES":"VC","ST. VINCENT AND THE GRENADINES":"VC","SAMOA":"WS","SAN MARINO":"SM","SAO TOME AND PRINCIPE":"ST","SAO TOME-PRINCIPE":"ST","SAUDI ARABIA":"SA","SENEGAL":"SN","SERBIA":"RS","SEYCHELLES":"SC","SIERRA LEONE":"SL","SINGAPORE":"SG","SINT MAARTEN (DUTCH PART)":"SX","SLOVAKIA":"SK","SLOVENIA":"SI","SOLOMON ISLANDS":"SB","SOMALIA":"SO","SOUTH AFRICA":"ZA","SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS":"GS","SOUTH SUDAN":"SS","SPAIN":"ES","SRI LANKA":"LK","SUDAN":"SD","SURINAME":"SR","SURINAM":"SR","SVALBARD AND JAN MAYEN":"SJ","SWAZILAND":"SZ","SWEDEN":"SE","SWITZERLAND":"CH","SYRIAN ARAB REPUBLIC":"SY","SYRIA":"SY","TAIWAN":"TW","TAJIKISTAN":"TJ","TANZANIA, UNITED REPUBLIC OF":"TZ","TANZANIA":"TZ","THAILAND":"TH","TIMOR-LESTE":"TL","EAST TIMOR":"TL","TOGO":"TG","TOKELAU":"TK","TONGA":"TO","TRINIDAD AND TOBAGO":"TT","TUNISIA":"TN","TURKEY":"TR","TURKMENISTAN":"TM","TURKS AND CAICOS ISLANDS":"TC","TURKS AND CAICOS":"TC","TUVALU":"TV","UGANDA":"UG","UKRAINE":"UA","UNITED ARAB EMIRATES":"AE","UNITED KINGDOM":"GB","UNITED STATES":"US","UNITED STATES MINOR OUTLYING ISLANDS":"UM","URUGUAY":"UY","UZBEKISTAN":"UZ","VANUATU":"VU","VENEZUELA, BOLIVARIAN REPUBLIC OF":"VE","VENEZUELA":"VE","VIET NAM":"VN","VIETNAM":"VN","BRITISH VIRGIN ISLANDS":"VG","VIRGIN ISLANDS, U.S.":"VI","WALLIS AND FUTUNA":"WF","WESTERN SAHARA":"EH","YEMEN":"YE","ZAMBIA":"ZM","ZIMBABWE":"ZW","NETHERLANDS ANTILLES":"AN","U.S. PACIFIC TRUST TERRITORIES":"TT"}

require('./small-arms3');

srcData.timeBins.forEach(o=> {
    o.data.forEach(x=> {
        x.i = cc[x.i.toUpperCase()]
        x.e = cc[x.e.toUpperCase()]
    });
    o.data.sort((a,b)=> b.v-a.v);
    // console.log(o.t,o.data.length)
})

x=JSON.stringify(srcData.timeBins);
console.log(x);

// $ node small-arms1.js
// 1992 2474
// 1993 2871
// 1994 3780
// 1995 3998
// 1996 4093
// 1997 4210
// 1998 4212
// 1999 4324
// 2000 4398
// 2001 4479
// 2002 4463
// 2003 4511
// 2004 4678
// 2005 4598
// 2006 4824
// 2007 4973
// 2008 4970
// 2009 4859
// 2010 4923
